config/routes.rb
Rails.application.routes.draw do
  root 'products#index'

  resources :products, only: [:index, :import] do
    collection do
      post :import
    end
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  validates :sku, uniqueness: true
  validates :price, :title, :sku, presence: true
  validates :price, format: { with: /\A\d{1,6}(\.\d{0,2})?\z/ }, numericality: { greater_than: 0 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  inherit_resources

  def import
    ImportWorker.perform_async(params[:file].tempfile.path)
    redirect_to :back
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
%html
  %head
    %title TestApp
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/products/_import.html.haml
%div
  %h3 Import a CSV File
  = form_tag import_products_path, multipart: true do
    = file_field_tag :file
    = submit_tag 'Import CSV'

app/views/products/_product.html.haml
%tr
  %td= product.sku
  %td= product.title
  %td= product.field1
  %td= product.field2
  %td= product.field3
  %td= product.field4
  %td= product.count
  %td= product.price

app/views/products/index.html.haml
= render 'import'

%table
  %thead
    %tr
      %th= 'SKU'
      %th= 'title'
      %th= 'field1'
      %th= 'field2'
      %th= 'field3'
      %th= 'field4'
      %th= 'count'
      %th= 'price'
  %tbody
    = render partial: 'product', collection: @products